### ISSUE TITLE
Error module.js:682

### ISSUE THREAD

**Issue by Aquive** [albrechtm85/cryptool#1]
module.js:682
    throw err;
    ^
SyntaxError: /home/.../Code/cryptool/config.json: Unexpected token / in JSON at position 6
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.../Code/cryptool/tool.js:2:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

**Comment by albrechtm85** [comment]
Used "//" in config.json, fixed in commit 1afa3176ad61537be7ea1d98d06179d8a1ea623b

**Comment by D3M3NTOS** [comment]
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bot/site.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
